---
title: "Analysis"
output: html_document
---

```{r, include = F}
library(tidyverse)
library(broom)
library(scales)
library(openxlsx)
library(knitr)
library(kableExtra)
library(usa)
library(psych)

#Load data
quant <- readRDS("S:\\COPE\\Data\\FUS\\220429 COPE FUS Clean Quantitative Responses.rds")
qual <- read.xlsx("S:\\COPE\\Data\\FUS\\Coded Qualitative Responses\\Depression Causes Master Codes.xlsx",
                  startRow = 3)

#Join
df <- left_join(quant, qual, "responseid")

#Rename variables for easy outputs
df <- df %>%
  rename(
    Race = race,
    Gender = gender,
    `Sexual Orientation` = orientation,
    Age = age,
    `Lack of Control` = lack_of_control,
    `Lack of Mental Health Supports` = lack_of_mental_health_support,
    `Lack of Hope or Certainty About the Future` = lack_of_hope_certainty,
    `Social Comparison` = social_comparison,
    `Body Image` = body_image,
    `Low Self-Worth` = low_self_worth,
    `School` = school,
    `Work` = work,
    `Unspecified Stress or Emotional Distress` = unspecified_stress,
    Biogenetic = biogenetic,
    Hereditary = hereditary,
    `Other Physical or Mental Health Issues` = other_disorder,
    `Adverse Childhood Events` = adverse_childhood,
    `Trauma/Abuse/Neglect at an Unspecified Time` = trauma_unsp,
    Grief = grief,
    `Dysfunctional Home/Family Relationships` = dysfunction_home,
    `Dysfunctional Peer Relationships` = dysfunction_peer,
    `Loneliness/Isolation` = loneliness,
    `Community/Systems` = community,
    `Global/Social Problems` = global_social_problems,
    `Social Media/Internet Use` = social_media,
    `Unspecified Environment` = environment_unsp,
    `Identity-Related Stressors` = identity,
    `Pressure or External Expectations` = pressure_expectations,
    `No Idea` = no_idea,
    `Just Happens` = just_happens,
    `Different for Everybody` = different_for_everybody,
    Count = count
  ) %>%
  mutate(responseType = recode(responseType,
                               "Personal" = "For Myself",
                               "General" = "For Others"))

#Save list of codes
codes <- df %>%
  select(`Lack of Control`:Count) %>%
  names()
binaryCodes <- setdiff(codes, "Count")
```

## Reliability and Sample Description

```{r, echo = F}
quant %>%
  select(cdi_1:cdi_12) %>%
  psych::alpha()

quant %>%
  select(bhs_1:bhs_4) %>%
  psych::alpha()

quant %>%
  select(pi_shs_1:pi_shs_5) %>%
  psych::alpha()

df %>%
  left_join(usa::zipcodes, by = "zip") %>%
  count(state) %>%
  nrow()

df_demog <- df %>%
  select(responseid, Race, Gender, `Sexual Orientation`, Age, depression) %>%
  distinct()

count(df_demog, Race) %>%
  mutate(pct = percent(n / sum(n), accuracy = .01)) %>%
  kable() %>%
  kable_styling()

count(df_demog, Gender) %>%
  mutate(pct = percent(n / sum(n), accuracy = .01)) %>%
  kable() %>%
  kable_styling()

count(df_demog, `Sexual Orientation`) %>%
  mutate(pct = percent(n / sum(n), accuracy = .01)) %>%
  kable() %>%
  kable_styling()

df_demog %>%
  summarize(mean = round(mean(Age, na.rm = T), 2),
            sd = round(sd(Age, na.rm = T), 2)) %>%
  kable(caption = "Age") %>%
  kable_styling()

df_demog %>%
  summarize(mean = round(mean(depression, na.rm = T), 2),
            sd = round(sd(depression, na.rm = T), 2),
            at_least_10 = round(mean(depression >= 10, na.rm = T), 2)) %>%
  kable(caption = "CDI-2-SF") %>%
  kable_styling()
```

## Aim 1: Code Frequency

```{r, echo = F}
#Dataset for analysis 1: codes in each or either response
df_either <- df %>%
  pivot_longer(all_of(codes), names_to = "code") %>%
  select(responseid, responseType, code, value) %>%
  pivot_wider(names_from = responseType, values_from = value) %>%
  rowwise() %>%
  mutate(Either = max(`For Myself`, `For Others`, na.rm = T)) %>%
  ungroup()

#Analysis 1
df_either %>%
  filter(code != "Count") %>%
  group_by(code) %>%
  summarize(across(c(`For Myself`, `For Others`, Either),
                   ~ . %>%
                     mean(na.rm = T) %>%
                     percent(accuracy = .01))) %>%
  kable() %>%
  kable_styling()

df_either %>%
  filter(code != "Count") %>%
  group_by(code) %>%
  summarize(Either = mean(Either, na.rm = T)) %>%
  mutate(code = fct_reorder(code, Either)) %>%
  ggplot() +
    geom_col(aes(code, Either), fill = "skyblue") +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = "Percent Endorsed (Either for Myself or for Others)", label = percent_format(accuracy = 1)) +
    coord_flip() +
    theme_classic() +
    theme(text = element_text(size = 16)) +
    ggtitle("Most Commonly Endorsed Causes for Depression")
```

## Aim 2: Difference by Subject (Myself/Others)

```{r, echo = F}
df_aim_2 <- df %>%
  pivot_longer(all_of(codes), names_to = "code") %>%
  select(responseid, responseType, code, value) %>%
  pivot_wider(names_from = responseType, values_from = value)

#Analysis 2
out_2 <- tibble()
for(x in binaryCodes) {
  
  df_temp <- df_aim_2 %>%
    filter(code == x) %>%
    drop_na()
  
  if(sum(df_temp$`For Myself`) > 0 & sum(df_temp$`For Others`) > 0) {
    
    X2_temp <- mcnemar.test(df_temp$`For Myself`, df_temp$`For Others`)
    
  } else {
    
    X2_temp <- tibble(
      statistic = NA_real_,
      p.value = NA_real_
    )

  }
  
  out_temp <- tibble(
    code = x,
    prop_pers = mean(df_temp$`For Myself`),
    se_pers = sd(df_temp$`For Myself`) / sqrt(nrow(df_temp)),
    prop_gen = mean(df_temp$`For Others`),
    se_gen = sd(df_temp$`For Others`) / sqrt(nrow(df_temp)),
    X2 = X2_temp$statistic,
    p = X2_temp$p.value
  )
  
  out_2 <- rbind(out_2, out_temp)
  
}

out_2$p <- p.adjust(out_2$p, "BH")

out_2 %>%
  select(Code = code,
         `For Myself` = prop_pers,
         `For Others` = prop_gen,
         X2,
         p) %>%
  mutate(`For Myself` = percent(`For Myself`, accuracy = .01),
         `For Others` = percent(`For Others`, accuracy = .01),
         X2 = format(round(X2, 2), nsmall = 2),
         p = format(round(p, 3), nsmall = 3)) %>%
  arrange(Code) %>%
  kable() %>%
  kable_styling()

# Test count
counts <- df_aim_2 %>%
  filter(code == "Count") %>%
  drop_na()

t.test(counts$`For Myself`, counts$`For Others`, paired = T)

mean(counts$`For Myself`)
sd(counts$`For Myself`)
mean(counts$`For Others`)
sd(counts$`For Others`)

# Plot significant predictors
out_2 %>%
  filter(p < .05) %>%
  pivot_longer(c(prop_gen, prop_pers, se_gen, se_pers),
               names_sep = "_",
               names_to = c("statistic", "category")) %>%
  pivot_wider(names_from = statistic,
              values_from = value) %>%
  mutate(category = recode(category,
                           "gen" = "For Others",
                           "pers" = "For Myself")) %>%
  ggplot() +
    geom_col(aes(category, prop), fill = "skyblue") +
    geom_errorbar(aes(category, ymin = prop - se, ymax = prop + se),
                  width = .4, color = "orange", size = 1) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = NULL, label = percent) +
    facet_wrap(~ code,
               scales = "free",
               ncol = 2) +
    theme_classic() +
    theme(text = element_text(size = 16)) +
    ggtitle("Perceived Causes of Depression, for Myself and for Others",
            "Means and Standard Errors")

# Social Media/Internet Use Only
out_2 %>%
  filter(code == "Social Media/Internet Use") %>%
    pivot_longer(c(prop_gen, prop_pers, se_gen, se_pers),
               names_sep = "_",
               names_to = c("statistic", "category")) %>%
    pivot_wider(names_from = statistic,
              values_from = value) %>%
  mutate(category = recode(category,
                           "gen" = "...For Others",
                           "pers" = "...For Themselves")) %>%
  ggplot() +
    geom_col(aes(category, prop), fill = "skyblue") +
    geom_errorbar(aes(category, ymin = prop - se, ymax = prop + se),
                  width = .4, color = "orange", size = 1) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = NULL, label = percent_format(accuracy = 1)) +
    theme_classic() +
    theme(text = element_text(size = 16)) +
    ggtitle("Adolescents Who Believe That Social Media/\nInternet Use Causes Depression...")
```

## Aim 3: Demographic Predictors

```{r, echo = F}
out_3 <- tibble()

for(x in c("Race", "Gender", "Sexual Orientation", "Age")) {
  
  if(x %in% c("Race", "Gender", "Sexual Orientation")) {
    
    categories_to_keep <- df %>%
      count(get(x)) %>%
      filter(n >= 50) %>% #25*2 responses
      mutate(categories = as.character(`get(x)`)) %>%
      pull(categories)
    
    df_temp_1 <- df %>%
      filter(get(x) %in% categories_to_keep)
    
  } else {
    
    df_temp_1 <- df
    
  }
  
  for(y in binaryCodes) {
    
    for(z in c("For Myself", "For Others")) {
      
      df_temp_2 <- df_temp_1 %>%
        filter(responseType == z)
      
      regression <- glm(
        data = df_temp_2,
        formula = as.formula(paste0("`", y, "` ~ `", x, "`")),
        family = "binomial"
      ) %>%
        tidy() %>%
        filter(term != "(Intercept)") %>%
        mutate(OR = exp(estimate), 
               outcome = y,
               responseType = z)
        
      out_3 <- rbind(out_3, regression)

    }
    
  }
  
}

out_3$p.value <- p.adjust(out_3$p.value, "fdr")

out_3 %>%
  filter(p.value < .1) %>%
  arrange(p.value)

df %>%
  filter(responseType == "For Myself") %>%
  drop_na(`Pressure or External Expectations`) %>%
  group_by(Race) %>%
  summarize(yes = sum(`Pressure or External Expectations` == 1),
            no = sum(`Pressure or External Expectations` == 0),
            mean = mean(`Pressure or External Expectations`))
```

## Aim 4: Associations with Related Constructs

```{r, echo = F}
DVs <- c("dep_permanence", "helpful_therapy", "helpful_meds", "depression", "hopelessness", "selfHate")

out_4 <- tibble()

for(x in codes) {
  
  for(y in DVs) {
    
    for(z in c("For Myself", "For Others")) {
      
      code <- df[[x]][df$responseType == z]
      DV <- df[[y]][df$responseType == z]

      test <- cor.test(code, DV, use = "complete.obs")
    
      out_4 <- rbind(
        out_4,
        tibble(
          code = x,
          DV = y,
          responseType = z,
          r = test$estimate,
          lower = test$conf.int[1],
          upper = test$conf.int[2],
          p = test$p.value
        )
      )
      
    }
    
  }
  
}

out_4$p <- p.adjust(out_4$p, "BH")

out_4 %>%
  filter(p < .1) %>%
  arrange(p)

out_4 %>%
  filter(code == "Hereditary" & DV == "helpful_meds" |
         code == "Adverse Childhood Events" & DV == "depression")
```

## Robustness Check

```{r, echo = F}
checkCode <- function(x) {
  
  temp <- table(df$studyGroup, df[[x]])
  results <- chisq.test(temp)
  return(results$p.value)
  
}

out_z <- sapply(binaryCodes, checkCode)
out_z <- p.adjust(out_z, "BH")
out_z
```

## Appendix: Gender Minority Predictor

```{r, echo = F}
df$genderMinority <- df$Gender == "Gender Minority"

out_3 <- tibble()

for(x in c("Race", "Gender", "Sexual Orientation", "Age", "genderMinority")) {
  
  if(x %in% c("Race", "Gender", "Sexual Orientation", "genderMinority")) {
    
    categories_to_keep <- df %>%
      count(get(x)) %>%
      filter(n >= 50) %>% #25*2 responses
      mutate(categories = as.character(`get(x)`)) %>%
      pull(categories)
    
    df_temp_1 <- df %>%
      filter(get(x) %in% categories_to_keep)
    
  } else {
    
    df_temp_1 <- df
    
  }
  
  for(y in codes) {
    
    for(z in c("For Myself", "For Others")) {
      
      df_temp_2 <- df %>%
        filter(responseType == z)
      
      regression <- glm(
        data = df_temp_2,
        formula = as.formula(paste0("`", y, "` ~ `", x, "`"))
      ) %>%
        tidy() %>%
        filter(term != "(Intercept)") %>%
        mutate(OR = exp(estimate), 
               outcome = y,
               responseType = z)
        
      out_3 <- rbind(out_3, regression)

    }
    
  }
  
}

out_3$p.value <- p.adjust(out_3$p.value, "fdr")

out_3 %>%
  filter(p.value < .1) %>%
  arrange(p.value)

df %>%
  filter(responseType == "For Myself") %>%
  group_by(Race) %>%
  summarize(mean = mean(`Pressure or External Expectations`, na.rm = T))
```
