---
title: "Symptom Beliefs Analysis"
output: html_document
---

```{r, include = F}
library(easypackages)
libraries("ggplot2", "scales", "knitr", "kableExtra", "rmcorr", "poLCA", "broom", "tidyverse")

df <- readRDS("S:\\COPE\\Data\\FUS\\220429 COPE FUS Clean Quantitative Responses.rds")
study_2_table_1 <- readRDS(file = "S:\\TRACK to TREAT\\Data\\Processed Data\\Table 1.rds")
study_2_combinations <- readRDS(file = "S:\\TRACK to TREAT\\Data\\Processed Data\\Combinations.rds")

# Rename symptoms to align with T2T variables
df <- df %>%
  rename(defInterest = dep_pleasure,
         defDown = dep_hopeless,
         defSleep = dep_sleep,
         defEnergy = dep_tired,
         defAppetite = dep_eat,
         defSelf = dep_esteem,
         defConcentrate = dep_concentrate,
         defPace = dep_movement,
         defSuicide = dep_ideation,
         defOther = dep_other,
         defNone = dep_none)

symptoms <- c("Interest", "Down", "Sleep", "Energy", "Appetite", "Self", "Concentrate", "Pace", "Suicide", "Other", "None")
symptoms_lca <- c("Interest", "Down", "Sleep", "Energy", "Appetite", "Self", "Concentrate", "Pace", "Suicide")
```

## Sample Description

```{r}
count(df, race) %>%
  mutate(pct = percent(n / sum(n), .01))
count(df, gender) %>%
  mutate(pct = percent(n / sum(n), .01))
count(df, orientation) %>%
  mutate(pct = percent(n / sum(n), .01))
count(df, age) %>%
  mutate(pct = percent(n / sum(n), .01))
mean(df$age, na.rm = T)
sd(df$age, na.rm = T)
```

## Analysis 1: Description of Symptom Beliefs

```{r}
table_1 <- df %>%
  select(all_of(paste0("def", symptoms))) %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(prop = mean(value, na.rm = T))

table_1 %>%
  mutate(pct = percent(prop, .01))
```

```{r}
table_1 %>%
  inner_join(study_2_table_1, by = "name", suffix = c("_1", "_2")) %>%
  pivot_longer(c("prop_1", "prop_2"),
               names_to = "study") %>%
  mutate(study = gsub("prop_", "Study ", study) %>%
           factor(levels = c("Study 2", "Study 1")),
         name = case_when(
           name == "defDown" ~ "Feeling Down",
           name == "defInterest" ~ "Little Interest",
           name == "defSleep" ~ "Trouble Sleeping",
           name == "defAppetite" ~ "Poor Appetite",
           name == "defEnergy" ~ "Little Energy",
           name == "defSelf" ~ "Feeling Bad About Yourself",
           name == "defConcentrate" ~ "Trouble Concentrating",
           name == "defPace" ~ "Psychomotor Symptoms",
           name == "defSuicide" ~ "Suicidal Ideation",
           name == "defOther" ~ "Other"
           ) %>%
           factor(levels = c("Feeling Down", "Little Interest", "Trouble Sleeping", "Poor Appetite", "Little Energy", "Feeling Bad About Yourself", "Trouble Concentrating", "Psychomotor Symptoms", "Suicidal Ideation", "Other"))) %>%
  ggplot(aes(name, value, group = study)) +
    geom_col(aes(fill = study), position = "dodge") +
    scale_x_discrete(name = NULL, limits = rev) +
    scale_y_continuous(name = "Percent Endorse", limits = c(0, 1), labels = percent) +
    scale_fill_grey(name = NULL, limits = rev) +
    coord_flip() +
    ggtitle("Beliefs About What Symptoms Constitute Depression") +
    theme_classic()
```

"Other" symptoms

```{r} 
df %>%
  pull(dep_other_text) %>%
  unique()
```

How many endorsed all DSM symptoms?

```{r}
df %>%
  select(responseid, matches("def"), -defOther, -defNone) %>%
  pivot_longer(matches("def")) %>%
  group_by(responseid) %>%
  summarize(prop_symptoms_endorsed = mean(value)) %>%
  count(prop_symptoms_endorsed) %>%
  mutate(total = sum(n),
         prop = n / sum(n))
```

Symptom combinations

```{r}
study_1_combinations <- df %>%
  mutate(combination = paste(defInterest,
                             defDown,
                             defSleep,
                             defEnergy,
                             defAppetite,
                             defSelf,
                             defConcentrate,
                             defPace,
                             defSuicide,
                             defOther,
                             dep_other_text)) %>%
  pull(combination) %>%
  unique()

study_2_combinations <- readRDS(file = "S:\\TRACK to TREAT\\Data\\Processed Data\\Combinations.rds")

combinations <- unique(c(study_1_combinations, study_2_combinations))
combinations <- setdiff(combinations, "NA NA NA NA NA NA NA NA NA NA NA")
length(combinations)
```

## Analysis 2: LCA

```{r}
df_lca <- df %>%
  mutate(across(all_of(paste0("def", symptoms_lca)), ~ . + 1))

f <- with(df_lca, cbind(defInterest, defDown, defSleep, defEnergy, defAppetite, defSelf, defConcentrate, defPace, defSuicide)) ~ 1

lca1 <- poLCA(f, df_lca, nclass = 1)
lca2 <- poLCA(f, df_lca, nclass = 2)
lca3 <- poLCA(f, df_lca, nclass = 3)
lca4 <- poLCA(f, df_lca, nclass = 4)
lca5 <- poLCA(f, df_lca, nclass = 5)

tibble(
  classes = 1:5,
  AIC = c(lca1$aic, lca2$aic, lca3$aic, lca4$aic, lca5$aic),
  BIC = c(lca1$bic, lca2$bic, lca3$bic, lca4$bic, lca5$bic)
)

df$class <- as.factor(3 - lca2$predclass)
```

```{r}
df %>%
  pivot_longer(all_of(paste0("def", symptoms_lca))) %>%
  group_by(class, name) %>%
  summarize(n = n(),
            mean = mean(value),
            se = sd(value) / sqrt(n())) %>%
  group_by(class, n) %>%
  summarize(mean = percent(mean(mean), .01))
```

```{r}
df %>%
  pivot_longer(all_of(paste0("def", symptoms_lca))) %>%
  group_by(class, name) %>%
  summarize(mean = mean(value),
            se = sd(value) / sqrt(n()),
            .groups = "drop") %>%
  mutate(name = case_when(
           name == "defDown" ~ "Feeling Down",
           name == "defInterest" ~ "Little Interest",
           name == "defSleep" ~ "Trouble Sleeping",
           name == "defAppetite" ~ "Poor Appetite",
           name == "defEnergy" ~ "Little Energy",
           name == "defSelf" ~ "Feeling Bad About Yourself",
           name == "defConcentrate" ~ "Trouble Concentrating",
           name == "defPace" ~ "Psychomotor Symptoms",
           name == "defSuicide" ~ "Suicidal Ideation",
           name == "defOther" ~ "Other"
           ) %>%
           factor(levels = c("Feeling Down", "Little Interest", "Trouble Sleeping", "Poor Appetite", "Little Energy", "Feeling Bad About Yourself", "Trouble Concentrating", "Psychomotor Symptoms", "Suicidal Ideation", "Other"))) %>%
  ggplot(aes(x = name, y = mean, group = class, linetype = class)) +
    geom_point() +
    geom_line() +
    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .5) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = "Percent Endorse", limits = c(0, 1), labels = percent) +
    scale_linetype_discrete(name = "Class") +
    ggtitle("Beliefs About What Symptoms Constitute Depression by Class") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Analysis 3: t-Tests

```{r}
t.test(df$depression ~ df$class)
t.test(df$hopelessness ~ df$class)
t.test(df$dep_permanence ~ df$class)
t.test(df$helpful_therapy ~ df$class)
t.test(df$helpful_meds ~ df$class)
```

```{r}
df %>%
  pivot_longer(c(depression, hopelessness, dep_permanence, helpful_therapy, helpful_meds)) %>%
  group_by(class, name) %>%
  summarize(mean = mean(value, na.rm = T),
            sd = sd(value, na.rm = T),
            n = n(),
            se = sd(value, na.rm = T) / sqrt(sum(!is.na(value))),
            ci = se * 1.96) %>%
  mutate(name = case_when(
    name == "depression" ~ "Depression Symptom\nSeverity",
    name == "hopelessness" ~ "Hopelessness",
    name == "dep_permanence" ~ "Perceived Permanence\nof Depression",
    name == "helpful_therapy" ~ "Perceived Helpfulness\nof Therapy",
    name == "helpful_meds" ~ "Perceived Helpfulness\nof Medication"
  )) %>%
  ggplot(aes(x = class, y = mean)) +
    geom_col(position = "dodge", fill = "lightgrey") +
    geom_errorbar(aes(ymin = mean - ci, ymax = mean + ci), color = "black", width = .5) +
    scale_x_discrete(name = "Class") +
    scale_y_continuous(name = NULL) +
    ggtitle("Clinical Variables by Class") +
    theme_classic() +
    facet_wrap(~ name, scales = "free")
```

## Robustness Check

Are there differences by study group?

```{r}
chisq.test(table(df$studyGroup, df$class))
```

Are there differences by treatment history?

```{r}
chisq.test(table(df$txHist_received, df$class))
chisq.test(table(df$txHist_received %in% c("Yes, now", "Yes, in the past"), df$class))
```
